"""One arm fingerprint at parity with itself, for the harness tests to vary one field at a time."""

from parity import ArmFingerprint

BASE = ArmFingerprint(
    router="mob",
    seed=42,
    deterministic=True,
    model_id="tiny",
    dtype="float32",
    dataset="wikitext/wikitext-2-raw-v1",
    max_steps=400,
    batch_size=2,
    gradient_accumulation_steps=8,
    max_seq_length=512,
    learning_rate=2e-5,
    warmup_steps=40,
    weight_decay=0.01,
    num_experts=4,
    top_k=2,
    adapter_rank=32,
    requested_layers=(5, 6, 7),
    use_lora=False,
    lora_rank=16,
    lora_alpha=32,
    lora_dropout=0.05,
    calibration_loss_weight=0.15,
    exploration_rate=0.02,
    confidence_head_learning_rate=5e-3,
    wealth_update_frequency=1,
    coupling_goal=None,
    coupling_beta=0.1,
    coupling_warmup_steps=100,
    gradient_checkpointing=True,
    device="cpu",
    probe_tokens=4096,
    eval_split="abc123",
    data_order="def456",
    converted_layers=3,
)
